# Generated by Django 4.0.1 on 2022-01-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='is_lecture_public',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_file',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_transcript',
        ),
        migrations.AddField(
            model_name='lecture',
            name='audio_file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='transcript',
            field=models.CharField(default='', max_length=25000),
        ),
    ]
