# Generated by Django 4.0.1 on 2022-01-30 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_lecture_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_public',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 3, 51, 2, 938985, tzinfo=utc)),
        ),
    ]
