# Generated by Django 4.0.1 on 2022-01-30 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0004_remove_lecture_is_public_lecture_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
