# Generated by Django 4.0.1 on 2022-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_alter_lecture_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='transcript',
            field=models.JSONField(default={'Summary': 'Processing...'}),
        ),
    ]
