# Generated by Django 4.0.1 on 2022-01-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_lecture_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='transcript',
        ),
        migrations.AddField(
            model_name='lecture',
            name='summary',
            field=models.JSONField(default={'Summary': 'Processing...'}),
        ),
    ]
